[package]
name = "xtask"
version = "0.0.0"
edition = "2024"
publish = false

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.60", features = ["derive"] }
image = "0.25.10"
imageproc = "0.27.0"
qrcode = "0.14.1"
tar = "0.4.45"
thiserror = "2.0.18"
